allow to set base href on compilation time
linagora/esn-frontend-contacts pull request #156
Opened 2021-06-08 21:52 UTC by asmaNode

2021-06-09 08:08 UTC, renaudboyer commented on webpack.commons.js
> +const BASE_HREF = process.env.BASE_HREF || '/contacts';
It needs a trailing slash

2021-06-09 08:08 UTC, alagane requested changes

2021-06-09 08:08 UTC, alagane commented on webpack.commons.js
> +const BASE_HREF = process.env.BASE_HREF || '/contacts';
The default should end with a `/`
```suggestion
const BASE_HREF = process.env.BASE_HREF || '/contacts/';
```

2021-06-10 07:22 UTC, fabienmoyon approved these changes

2021-06-10 07:39 UTC, alagane approved these changes

2021-06-10 08:18 UTC, merged